[package]
name = "microkit-http-server-example-server"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
async-unsync = { version = "0.2.2", default-features = false }
futures = { version = "0.3.28", default-features = false, features = ["async-await", "alloc"] }
log = "0.4.17"
microkit-http-server-example-server-core = { path = "./core", features = [] }
sel4 = { path = "../../../../../sel4" }
sel4-async-block-io = { path = "../../../../../sel4-async/block-io" }
sel4-async-block-io-fat = { path = "../../../../../sel4-async/block-io/fat" }
sel4-async-network = { path = "../../../../../sel4-async/network" }
sel4-async-request-statuses = { path = "../../../../../sel4-async/request-statuses" }
sel4-async-timer-manager = { path = "../../../../../sel4-async/timer-manager" }
sel4-bounce-buffer-allocator = { path = "../../../../../sel4-bounce-buffer-allocator" }
sel4-immediate-sync-once-cell = { path = "../../../../../sel4-immediate-sync-once-cell" }
sel4-logging = { path = "../../../../../sel4-logging" }
sel4-microkit-message = { path = "../../../../../sel4-microkit/message" }
sel4-shared-ring-buffer = { path = "../../../../../sel4-shared-ring-buffer" }
sel4-shared-ring-buffer-block-io = { path = "../../../../../sel4-shared-ring-buffer/block-io" }
sel4-shared-ring-buffer-smoltcp = { path = "../../../../../sel4-shared-ring-buffer/smoltcp" }
sel4-sync = { path = "../../../../../sel4-sync" }

[dependencies.microkit-http-server-example-sp804-driver-interface-types]
path = "../sp804-driver/interface-types"

[dependencies.microkit-http-server-example-virtio-blk-driver-interface-types]
path = "../virtio-blk-driver/interface-types"

[dependencies.microkit-http-server-example-virtio-net-driver-interface-types]
path = "../virtio-net-driver/interface-types"

[dependencies.sel4-async-single-threaded-executor]
path = "../../../../../sel4-async/single-threaded-executor"

[dependencies.sel4-externally-shared]
path = "../../../../../sel4-externally-shared"
features = ["unstable", "alloc"]

[dependencies.sel4-microkit]
path = "../../../../../sel4-microkit"
default-features = false
features = ["alloc"]

[dependencies.sel4-newlib]
path = "../../../../../sel4-newlib"
features = ["nosys", "all-symbols", "sel4-panicking-env"]

[dependencies.sel4-shared-ring-buffer-block-io-types]
path = "../../../../../sel4-shared-ring-buffer/block-io/types"

[dependencies.smoltcp]
version = "0.10.0"
default-features = false
features = ["proto-ipv4", "proto-dhcpv4", "proto-dns", "socket-dhcpv4", "socket-dns", "socket-tcp"]

[build-dependencies]
rcgen = "0.11.1"
