[package]
name = "banscii-artist"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
banscii-artist-interface-types = { path = "./interface-types" }
rsa = { version = "0.8.1", default-features = false, features = ["pem", "sha2"] }
sel4-externally-shared = { path = "../../../../../sel4-externally-shared", features = ["unstable"] }
sel4-microkit-message = { path = "../../../../../sel4-microkit/message" }

[dependencies.sel4-microkit]
path = "../../../../../sel4-microkit"
default-features = false
features = ["alloc"]

[build-dependencies]
rsa = "0.8.1"
