#
# Copyright 2023, Colias Group, LLC
#
# SPDX-License-Identifier: BSD-2-Clause
#

[package]
name = "sel4-async-block-io"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[features]
alloc = ["futures/alloc", "lru"]
default = ["alloc"]

[dependencies]
bytemuck = { version = "1.4.0", default-features = false }
futures = { version = "0.3.28", default-features = false }
gpt_disk_types = { version = "0.15.0", features = ["bytemuck"] }
log = "0.4.17"
lru = { version = "0.10.0", optional = true }
num_enum = { version = "0.5.9", default-features = false }
