[package]
name = "sel4-simple-task-runtime"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[features]
alloc = [
    "sel4-backtrace/alloc",
    "sel4-backtrace-simple/alloc",
    "sel4-simple-task-threading/alloc",
    "serde_json?/alloc"
]
default = ["serde_json", "alloc"]
serde_json = ["dep:serde_json"]

[dependencies]
postcard = { version = "1.0.2", default-features = false }
sel4 = { path = "../../../../sel4" }
sel4-backtrace = { path = "../../../../sel4-backtrace", features = ["unwinding", "postcard"] }
sel4-backtrace-simple = { path = "../../../../sel4-backtrace/simple" }
sel4-dlmalloc = { path = "../../../../sel4-dlmalloc" }
sel4-immediate-sync-once-cell = { path = "../../../../sel4-immediate-sync-once-cell" }
sel4-panicking = { path = "../../../../sel4-panicking" }
sel4-panicking-env = { path = "../../../../sel4-panicking/env" }
sel4-reserve-tls-on-stack = { path = "../../../../sel4-reserve-tls-on-stack" }
sel4-runtime-common = { path = "../../../../sel4-runtime-common", features = ["tls", "unwinding"] }
sel4-simple-task-runtime-config-types = { path = "./config/types" }
sel4-simple-task-runtime-macros = { path = "./macros" }
sel4-simple-task-threading = { path = "../threading" }
sel4-sync = { path = "../../../../sel4-sync" }
serde = { version = "1.0.147", default-features = false }
serde_json = { version = "1.0.87", default-features = false, optional = true }
