#
# Copyright 2023, Colias Group, LLC
#
# SPDX-License-Identifier: BSD-2-Clause
#

[package]
name = "sel4-async-block-io-fat"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
futures = { version = "0.3.28", default-features = false, features = ["alloc"] }
heapless = "0.7.16"
hex = { version = "0.4.3", default-features = false }
log = "0.4.17"
lru = "0.10.0"
sel4-async-block-io = { path = ".." }

[dependencies.embedded-fat]
git = "https://github.com/coliasgroup/rust-embedded-fat.git"
tag = "keep/e1465a43c9f550ef58701a275b313310"
