[package]
name = "sel4-backtrace-cli"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
addr2line = "0.21.0"
clap = "4.4.6"
hex = "0.4.3"
memmap = "0.7.0"
object = "0.32.1"
sel4-backtrace-types = { path = "../types", features = ["full"] }
