#
# Copyright 2023, Colias Group, LLC
#
# SPDX-License-Identifier: BSD-2-Clause
#
#

[workspace]
resolver = "2"
members = [
    "crates/toml-path-regex",
    "crates/toml-normalize",
    "crates/manage-cargo-manifests",
]
