[package]
name = "sel4-shared-ring-buffer-block-io-types"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
num_enum = { version = "0.5.9", default-features = false }
sel4-shared-ring-buffer = { path = "../.." }
zerocopy = { version = "0.7.6", features = ["derive"] }
