[package]
name = "banscii-assistant-core"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
ab_glyph = { version = "0.2.22", default-features = false, features = ["libm"] }
libm = { version = "0.2.1", default-features = false }
log = "0.4.17"
